PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE topics 
			(topic_id int, topic_name text);
INSERT INTO topics VALUES(0,'water, transportation');
INSERT INTO topics VALUES(2,'service');
INSERT INTO topics VALUES(3,'health');
INSERT INTO topics VALUES(5,'license');
INSERT INTO topics VALUES(6,'crime');
INSERT INTO topics VALUES(7,'transit');
INSERT INTO topics VALUES(8,'law');
INSERT INTO topics VALUES(9,'public_space');
INSERT INTO topics VALUES(11,'community');
INSERT INTO topics VALUES(12,'education');
INSERT INTO topics VALUES(14,'budget');
INSERT INTO topics VALUES(16,'zoning');
INSERT INTO topics VALUES(17,'espanol');
INSERT INTO topics VALUES(18,'procedural');
INSERT INTO topics VALUES(19,'housing');
INSERT INTO topics VALUES(20,'plenary');
INSERT INTO topics VALUES(21,'land');
INSERT INTO topics VALUES(24,'public_safety');
INSERT INTO topics VALUES(25,'mental_health');
INSERT INTO topics VALUES(26,'public_health');
INSERT INTO topics VALUES(27,'climate_change');
INSERT INTO topics VALUES(28,'agriculture');
INSERT INTO topics VALUES(29,'utilities');
INSERT INTO topics VALUES(30,'legal');
INSERT INTO topics VALUES(32,'transportation');
INSERT INTO topics VALUES(33,'economy');
INSERT INTO topics VALUES(34,'immigration');
COMMIT;
